#!/usr/bin/env bash
#
# 'apt-snapshot'. Manage snapshots of root filesystem before APT operations.
# Copyright © 2016-2017 Mathias Bocquet (mbocquet@sekoya.org)

DEFAULT="/etc/default/$(basename $0)"
. $DEFAULT

# Remove previous snapshots keeping SNAP_HISTORY_KEEP
# Get old snapshots list
SNAPS="$(lvs --noheadings -o lv_path -S origin=${ORIGIN_LV})"
SNAP_COUNT="$(echo $SNAPS|wc -w)"
# Delete 1+ SNAP_COUNT - SNAP_HISTORY_KEEP
SNAPS_TO_DELETE=$((1 + $SNAP_COUNT - $SNAP_HISTORY_KEEP))
if [ "$SNAPS_TO_DELETE" -gt "0" ]
then
    lvremove $(echo $SNAPS|cut -d' ' -f-${SNAPS_TO_DELETE}) -f
fi

# Create a new snapshot
lvcreate --snapshot -l ${PERCENT_SIZE}ORIGIN -i ${SNAP_DEVICES_COUNT:=1} /dev/${ORIGIN_VG}/${ORIGIN_LV} -n ${ORIGIN_LV}_$(date +%Y%m%d-%H%M%S) $SNAP_DEVICES
